### PR TITLE
Use a smaller custom polyfill

### PR DESCRIPTION
**Pull request by arv**
This is a custom build of only CustomElement + HTMLImports

 Built using `grunt build-lite` from https://github.com/Polymer/platform-dev

### CODE REVIEW

**Comment by bterlson** [comment]
Can you also include this at spec/index.html? Need to remove layout.html but still want to support tasks/build until I can get the spec/index.html version working cross-browser...

**Comment by arv** [comment]
Done.

**Comment by arv** [comment]
Do you want me to squash? Do you care?

**Comment by bterlson** [comment]
I care not, thanks!!

**Pull request merged**
