### PR TITLE
Use attached callback instead of created callback

### PR DESCRIPTION
**Pull request by arv**
Also a bunch of minor cleanups.

### CODE REVIEW

**Comment by arv** [comment]
It is still unclear to me why `setTimeout(f, 0)` does not work.

**Comment by arv** [comment]
Hold off this... I see some issues

**Comment by bterlson** [comment]
I was just about to point out odd header behavior... I suspect that's what you're looking into presently?

**Comment by arv** [comment]
PTAL

**Comment by bterlson** [comment]
Works great!

Thanks for including a better implementation of es-clause! It's good to see an example of a reasonable factoring of a custom element.

**Pull request merged**
